# Generated by Django 5.1.1 on 2024-09-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
